### ISSUE TITLE
Write backup to any stream

### ISSUE THREAD

**Issue by palmerabollo** [hex7c0/mongodb-backup#1]
It would be great to be able to dump the backup to any nodejs stream, not only files.

In some cloud environments you don't have access to a filesystem but you could easily write it as a response to a HTTP request.

I haven't evaluated how hard it would be to implement this.

**Comment by hex7c0** [comment]
like this [example](https://github.com/hex7c0/mongodb-backup/blob/master/examples/web_stream.js)?

obviously you can send dump only via `.tar`
however I've a big trouble with packer*, it saves only 1 `bson` doc

**Comment by palmerabollo** [comment]
Yes! But why do you say you need to write a .tar file? (In my use case I don't have privileges to write to the filesystem)

I've seen some modules that are able to stream a mongodb dump ([example](https://www.npmjs.com/package/mongodump-stream)) without writing a file, but I don't if the same technique would be applicable to mongodb-backup.

**Comment by hex7c0** [comment]
you cannot send a directory to HTTP (or stream)
you should pack your files into a tar file before, and write it to stream

you cannot write into a tmp dir?
