### ISSUE TITLE
Int64 _id gets exported as a TimeStamp

### ISSUE THREAD

**Issue by smlgbl** [hex7c0/mongodb-backup#10]
When exporting/backup-ing a document with ID like this:

"_id" : "1000576093407275579" (Int64)

they end up being transformed to this:

"_id" : Timestamp(1833010877, -705238994)

This is with the standard BSON parser.
As a workaround I tried using the JSON parser, but that screws up all datatypes.
This does not happen with the standard mongodump/mongorestore tools, but they're also using BSON as intermediate format.

bsondump --type=debug says, the _id field is of type 1, which is Double, from the mongodump BSON file,
but it's of type 17 (=TimeStamp) in the BSON file from mongodb-backup.

**Comment by hex7c0** [comment]
thanks for the issue
I'll check it out

https://github.com/hex7c0/mongodb-restore/issues/8

**Comment by hex7c0** [comment]
I'll check this issue on restore module
