### ISSUE TITLE
Delays server side functions on meteorJS

### ISSUE THREAD

**Issue by rsercano** [hex7c0/mongodb-backup#11]
Hello,

first of all thanks for the great work on nodejs packages mongodb-backup and restore. I'm currently using these two packages in meteor js. And it suits my needs perfectly. 

But, I've an issue that mongodb-dump delays my other serverside functions. I mean whenever I call mongodb-backup, and then call another my server-side function, my function works a few seconds later.

Could you please have a look at it ?

Thanks in advance.

**Comment by rsercano** [comment]
Here's my code example:

```
try {
            backup({
                uri: connectionUrl,
                root: path,
                tar: fileName,
                callback: Meteor.bindEnvironment(function () {
                    // it comes here whenever it finishes and works...
                })
            });
        }
        catch (ex) {
            console.log('Unexpected exception during dump process: ', ex);
        }
```

Afterwards I'm calling another server-side function from the client-side: 

```
Meteor.call('blabla',callback);
```

But second function is being called 10-15 seconds later.

**Comment by rsercano** [comment]
Update:

appearently `collection.find(query).toArray(function (err, docs) {` calls in your package blocks the other server-side meteor functions work. Whenever collections iteration is over, the others work. In the meantime sometimes other server-side methods work but like 10-15 seconds delayed.

**Comment by rsercano** [comment]
Hello again,

I wanted to update you about improvements, with your latest version it seems to be working way better. Thanks for the heavy work.

**Comment by hex7c0** [comment]
with stream cursor (on 1.6.x), it seems solved
