### ISSUE TITLE
License (GPL)

### ISSUE THREAD

**Issue by aramk** [hex7c0/mongodb-backup#12]
Hi there, thanks for writing the awesome library. Would you consider changing the license to MIT for broader commercial uses? 😄

**Comment by hex7c0** [comment]
hi aramk,
I prefer migrate to Apache2 license

**Comment by aramk** [comment]
Yeah that's pretty similar and not copyleft. I was hoping to use this on AWS for a small business I'm building an app for. I'm sure it's not likely to be an issue, but it's quite a nice modular library that a lot of bigger apps could use.

**Comment by aramk** [comment]
👍 awesome

**Comment by spmiller** [comment]
Hi @hex7c0, thanks for updating this project's license to Apache2. I am concerned though that its dependencies are still licensed under AGPL: basic-authentication, logger-request, setheaders and transfer-rate. Doesn't this mean that by including mongodb-backup I trigger copyleft?

**Comment by hex7c0** [comment]
hi @spmiller,
I'm so sorry for this delay

I'll update License of deps

**Comment by spmiller** [comment]
Thanks @hex7c0!
