### ISSUE TITLE
Link to examples is broken

### ISSUE THREAD

**Issue by stephanvermeire** [hex7c0/mongodb-backup#13]
Hi,

First I want to thank you for your great work sofar on mongodb-backup.
I came across a small issue, as the title says: The link to examples is broken. Could this be fixed?

Thanx,
Stephan

**Comment by hex7c0** [comment]
hi Stephan,
what broken link are you referring to?
The link to the examples in README.md works fine in all branches https://github.com/hex7c0/mongodb-backup/tree/1.5/examples

**Comment by stephanvermeire** [comment]
mmm strange, yesterday I encountered some problems but now it appears to work perfectly.
Sorry about the fuzz, please consider this issue as resolved.

**Comment by hex7c0** [comment]
mmm maybe on npm website?
https://www.npmjs.com/package/mongodb-backup
