### ISSUE TITLE
EMFILE: Error with large number of db

### ISSUE THREAD

**Issue by Koldunz** [hex7c0/mongodb-backup#16]
Hello,
Thanks for the great work on nodejs packages mongodb-backup and restore. I'm currently using these two packages in my project.

I have some problems with large number of db. I try backup 100+ db in async.series. But I have error:
`fs.js:60
      throw err;  // Forgot a callback but don't know where? Use NODE_DEBUG=fs
      ^
Error: EMFILE: too many open files, open '/var/www/test/node_modules/mongodb-backup/dump/db_1/pages/577bc802fed786f67fdc43b3.bson'
at Error (native)`

The size of each base about 100 mb
Could you please have a look at it ?

Thanks in advance.

**Comment by hex7c0** [comment]
hey Koldunz,
which version do you use?

**Comment by Koldunz** [comment]
Nodejs v4.4.6
Npm v2.15.5
mongodb-backup v1.6.0

**Comment by hex7c0** [comment]
you should raise `ulimit -n 4096`

next release I'll use https://github.com/isaacs/node-graceful-fs

**Comment by Koldunz** [comment]
Thank you. I'll wait for the update

**Comment by hex7c0** [comment]
published https://github.com/hex7c0/mongodb-backup/releases/tag/1.6.1
