### ISSUE TITLE
Restoring the backup

### ISSUE THREAD

**Issue by ybrodsky** [hex7c0/mongodb-backup#17]
I have tried and search but without luck. How do you go about restoring the backup this module creates?

An example would be appreciated. Thanks

**Comment by hex7c0** [comment]
hey ybrodsky
in README.md you can find link for [`mongodb-restore`](https://github.com/hex7c0/mongodb-restore)

**Comment by ybrodsky** [comment]
Lol, damn tunnel vision. 

Thanks a lot.

**Comment by hex7c0** [comment]
you're welcome :)
