### ISSUE TITLE
update package with mongo driver 3

### ISSUE THREAD

**Issue by RezaErfani67** [hex7c0/mongodb-backup#34]
mongo driver 2 is old and there is some problems on query  with _id...
please update packege with mongo driver 3...
it need some changes such as snapshot stream or mongo client connection.

**Comment by Phoscur** [comment]
Duplicate of #27, see PR https://github.com/hex7c0/mongodb-backup/pull/36

**Comment by RezaErfani67** [comment]
thanks alot...
should install [this](https://www.npmjs.com/package/mongodb-backup-4x)
