### ISSUE TITLE
Version pulled out bson@0.4.11

### ISSUE THREAD

**Issue by YouriT** [hex7c0/mongodb-backup#5]
Hey @hex7c0,

bson@0.4.11 has been pulled out, could you remove the hard dep in your packages.json and push a new release to npm ? (cf mongodb/js-bson#147)
```json
    "bson": "0.4.11",
```
would become
```json
    "bson": "~0.4",
```

Thank you :)

**Comment by hex7c0** [comment]
hey @YouriT,
thanks for the notice, I'll release an update soon
