### ISSUE TITLE
Installation issue

### ISSUE THREAD

**Issue by sachinsawant71** [hex7c0/mongodb-backup#9]
I am trying to install mongodb_backup. I have Windows7 machine. 

I ram command -  npm install --save mongodb_backup. But I am getting an error - Registry returned 404 for GET on http://registry.npmjs.org/mongodb_backup error and mongodb_backup' is not in the npm registry

Details on my environment are - 

node v0.10.38
npm  v2.11.1

**Comment by hex7c0** [comment]
mmm the right endpoint is http://registry.npmjs.org/mongodb-backup

**Comment by sachinsawant71** [comment]
yes,
